import {env} from 'cloudflare:workers';
import {db,bucket} from '../db';
import {getUser,sessionCookie,clearedCookie,passwordMatches,authConfigured} from './auth';
import {DEMO_RECORD,normalizePlate,validateLookup,validateDetection} from './domain.mjs';
import {isOperator,checkOrigin,validLease} from './access.mjs';
type Row=Record<string,any>;
class HttpError extends Error {constructor(public status:number,message:string){super(message)}}
const json=(body:unknown,status=200)=>Response.json(body,{status,headers:{'Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}});
const MAX_UPLOAD=20*1024*1024;
const text=(v:unknown,max:number,label:string)=>{if(typeof v!=='string'||!v.trim()||v.trim().length>max)throw new HttpError(422,`${label} is required and must be under ${max+1} characters.`);return v.trim()};
async function input(req:Request,max=10000){const length=Number(req.headers.get('content-length'));if(length>max)throw new HttpError(413,'Request is too large.');const raw=await readBounded(req.body,max);try{const parsed=JSON.parse(new TextDecoder().decode(raw));if(!parsed||typeof parsed!=='object'||Array.isArray(parsed))throw new Error('object required');return parsed}catch{throw new HttpError(422,'Send a valid JSON object.')}}
async function readBounded(stream:ReadableStream<Uint8Array>|null,max:number){if(!stream)throw new HttpError(422,'Request body is required.');const reader=stream.getReader();const chunks:Uint8Array[]=[];let total=0;while(true){const {done,value}=await reader.read();if(done)break;total+=value.length;if(total>max){await reader.cancel();throw new HttpError(413,'Request is too large.')}chunks.push(value)}const bytes=new Uint8Array(total);let offset=0;for(const c of chunks){bytes.set(c,offset);offset+=c.length}return bytes}
async function hash(value:string){const out=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value));return Array.from(new Uint8Array(out)).map(n=>n.toString(16).padStart(2,'0')).join('')}
async function operator(req:Request){const user=await getUser(req);if(!user)throw new HttpError(401,'Sign in to use the operator workspace.');if(!isOperator(user.email,env.OPERATOR_EMAILS))throw new HttpError(403,'This account is not an approved operator.');return user}
async function worker(req:Request){const token=req.headers.get('authorization')?.replace(/^Bearer /,'');if(!token||token.length>160)throw new HttpError(401,'Worker key required.');const row=await db().prepare('SELECT * FROM worker_tokens WHERE token_hash = ? AND expires_at > ?').bind(await hash(token),Date.now()).first<Row>();if(!row)throw new HttpError(401,'Invalid or expired worker key.');await db().prepare('UPDATE worker_tokens SET last_seen = ? WHERE token_hash = ?').bind(Date.now(),row.token_hash).run();return row}
async function cleanupUpload(job:Row){await bucket().delete(job.object_key);await db().prepare("UPDATE jobs SET upload_deleted_at=? WHERE id=? AND status='completed'").bind(new Date().toISOString(),job.id).run()}
async function retryCleanup(owner:string){const rows=await db().prepare("SELECT id,object_key FROM jobs WHERE owner=? AND status='completed' AND upload_deleted_at IS NULL LIMIT 5").bind(owner).all<Row>();for(const row of rows.results){try{await cleanupUpload(row)}catch(e){console.warn('Upload cleanup pending',row.id)}}}
function publicRecord(r:Row){return {id:r.id,plate:r.plate,state:r.state,confidence:r.confidence,votes:r.votes,detected_at:r.detected_at,truck_id:r.truck_id,destination:r.destination,source_filename:r.source_filename,review_status:r.review_status,analyzed_frames:r.analyzed_frames,snapshot_url:r.snapshot_key?'/api/media/'+r.id:null,is_demo:false}}
function validate<T>(f:()=>T){try{return f()}catch(e){throw new HttpError(422,(e as Error).message)}}
async function limitLogin(req:Request){const ip=req.headers.get('cf-connecting-ip')||'local';const now=Date.now(),window=Math.floor(now/600000),key=await hash(`login:${env.LOOKUP_SALT||'towlookup'}:${ip}:${window}`);const row=await db().prepare('INSERT INTO lookup_limits (key,count,expires_at) VALUES (?,1,?) ON CONFLICT(key) DO UPDATE SET count=count+1 RETURNING count').bind(key,now+1200000).first<Row>();if(row&&row.count>10)throw new HttpError(429,'Too many sign-in attempts. Please wait ten minutes and try again.')}
async function limitLookup(req:Request){const ip=req.headers.get('cf-connecting-ip');if(!ip)return;const now=Date.now(),window=Math.floor(now/60000),key=await hash(`${env.LOOKUP_SALT||'towlookup'}:${ip}:${window}`);const row=await db().prepare('INSERT INTO lookup_limits (key,count,expires_at) VALUES (?,1,?) ON CONFLICT(key) DO UPDATE SET count=count+1 RETURNING count').bind(key,now+120000).first<Row>();if(row&&row.count>30)throw new HttpError(429,'Too many searches. Please wait a minute and try again.');await db().prepare('DELETE FROM lookup_limits WHERE expires_at < ?').bind(now).run()}
export async function handle(req:Request){try{
 const path=new URL(req.url).pathname.replace(/^\/api\//,'').replace(/\/$/,'');const method=req.method;
 if(!['GET','HEAD'].includes(method)&&!checkOrigin(req))throw new HttpError(403,'Cross-site request rejected.');
 if(path==='login'&&method==='POST'){if(!authConfigured())throw new HttpError(503,'Operator sign-in is not configured on this site yet.');await limitLogin(req);const body=await input(req);const email=typeof body.email==='string'?body.email.trim().toLowerCase():'';const password=typeof body.password==='string'?body.password.slice(0,200):'';const ok=await passwordMatches(password);if(!ok||!isOperator(email,env.OPERATOR_EMAILS))throw new HttpError(401,'That email and password were not accepted.');const res=json({signedIn:true,operator:true,displayName:email});res.headers.append('Set-Cookie',await sessionCookie(req,email));return res}
 if(path==='logout'&&method==='POST'){const res=json({signedOut:true});res.headers.append('Set-Cookie',clearedCookie(req));return res}
 if(path==='session'&&method==='GET'){const u=await getUser(req);return json({signedIn:!!u,operator:!!u&&isOperator(u.email,env.OPERATOR_EMAILS),displayName:u?.displayName})}
 if(path==='status'&&method==='GET'){await db().prepare('SELECT COUNT(*) AS count FROM records').first();const u=await getUser(req);let online=false;if(u&&isOperator(u.email,env.OPERATOR_EMAILS)){const w=await db().prepare('SELECT last_seen FROM worker_tokens WHERE owner = ? AND expires_at > ?').bind(u.userId,Date.now()).first<Row>();online=!!w&&w.last_seen>Date.now()-120000}return json({database:'ready',worker_online:online})}
 if(path==='lookup'&&method==='POST'){const body=await input(req);const {plate,state}=validate(()=>validateLookup(body));if(body.demo===true){return json({record:plate===DEMO_RECORD.plate&&state===DEMO_RECORD.state?DEMO_RECORD:null})}await limitLookup(req);const row=await db().prepare("SELECT * FROM records WHERE plate = ? AND state = ? AND review_status = 'published' ORDER BY detected_at DESC LIMIT 1").bind(plate,state).first<Row>();return json({record:row?publicRecord(row):null})}
 if(path==='records'&&method==='GET'){const u=await operator(req);const rows=await db().prepare('SELECT * FROM records WHERE owner = ? ORDER BY detected_at DESC LIMIT 100').bind(u.userId).all<Row>();return json({records:rows.results.map(publicRecord)})}
 if(path.startsWith('records/')&&method==='PATCH'){const u=await operator(req);const id=path.slice(8);const body=await input(req);if(!['published','rejected'].includes(body.status))throw new HttpError(422,'Choose published or rejected.');const row=await db().prepare('UPDATE records SET review_status = ?, reviewed_at = ? WHERE id = ? AND owner = ? RETURNING id').bind(body.status,new Date().toISOString(),id,u.userId).first();if(!row)throw new HttpError(404,'Record not found.');return json({updated:true})}
 if(path==='jobs'&&method==='GET'){const u=await operator(req);const rows=await db().prepare('SELECT id,source_filename,status,created_at,error,result_count FROM jobs WHERE owner = ? ORDER BY created_at DESC LIMIT 30').bind(u.userId).all();return json({jobs:rows.results})}
 if(path==='jobs'&&method==='POST'){
  const u=await operator(req);const pending=await db().prepare("SELECT COUNT(*) AS count FROM jobs WHERE owner = ? AND status IN ('queued','analyzing')").bind(u.userId).first<Row>();if(pending&&pending.count>=5)throw new HttpError(429,'Five videos are already waiting. Process them before uploading more.');
  if(Number(req.headers.get('content-length'))>MAX_UPLOAD+65536)throw new HttpError(413,'Choose a video under 20 MB.');
  if(!req.headers.get('content-type')?.startsWith('multipart/form-data'))throw new HttpError(422,'Send video as multipart form data.');const bytes=await readBounded(req.body,MAX_UPLOAD+65536);let form:FormData;try{form=await new Request(req.url,{method:'POST',headers:{'content-type':req.headers.get('content-type')||''},body:bytes}).formData()}catch{throw new HttpError(422,'The upload form could not be read. Try selecting the video again.')};const file=form.get('video');if(!file||typeof file==='string')throw new HttpError(422,'Choose a video.');if(!file.size||file.size>MAX_UPLOAD)throw new HttpError(413,'Choose a nonempty video under 20 MB.');const filename=file.name.replace(/[\\/\x00-\x1f]/g,'_').slice(0,180);if(!/\.(mp4|mov|webm|avi|mkv)$/i.test(filename))throw new HttpError(422,'Unsupported video format.');
  const state=validate(()=>validateLookup({plate:'VALID',state:form.get('state')})).state;const truck=text(form.get('truck_id'),50,'Camera ID');const destination=text(form.get('destination'),200,'Destination');const id=crypto.randomUUID(),key='uploads/'+id;await bucket().put(key,file.stream(),{httpMetadata:{contentType:'application/octet-stream'}});try{await db().prepare('INSERT INTO jobs (id,owner,source_filename,object_key,state,truck_id,destination,status,created_at,attempts) VALUES (?,?,?,?,?,?,?,?,?,0)').bind(id,u.userId,filename,key,state,truck,destination,'queued',new Date().toISOString()).run()}catch(e){await bucket().delete(key);throw e}return json({id,status:'queued'},201)
 }
 if(path==='worker/token'&&method==='POST'){const u=await operator(req);const token=Array.from(crypto.getRandomValues(new Uint8Array(32))).map(n=>n.toString(16).padStart(2,'0')).join('');await db().prepare('INSERT INTO worker_tokens (token_hash,owner,created_at,expires_at,last_seen) VALUES (?,?,?,?,NULL) ON CONFLICT(owner) DO UPDATE SET token_hash=excluded.token_hash,created_at=excluded.created_at,expires_at=excluded.expires_at,last_seen=NULL').bind(await hash(token),u.userId,new Date().toISOString(),Date.now()+90*86400000).run();return json({token,expires_in_days:90})}
 if(path==='worker/heartbeat'&&method==='POST'){const w=await worker(req);await retryCleanup(w.owner);return json({ok:true})}
 if(path==='worker/claim'&&method==='POST'){const w=await worker(req);await retryCleanup(w.owner);const now=Date.now(),lease=crypto.randomUUID();await db().prepare("UPDATE jobs SET status='failed',error='Analysis timed out after three attempts.' WHERE owner=? AND status='analyzing' AND lease_until < ? AND attempts >= 3").bind(w.owner,now).run();const job=await db().prepare("UPDATE jobs SET status='analyzing',lease_id=?,lease_until=?,attempts=attempts+1,error=NULL WHERE id=(SELECT id FROM jobs WHERE owner=? AND (status='queued' OR (status='analyzing' AND lease_until < ?)) AND attempts < 3 ORDER BY created_at LIMIT 1) RETURNING *").bind(lease,now+15*60000,w.owner,now).first<Row>();return json({job:job?{id:job.id,source_filename:job.source_filename,lease_id:job.lease_id,state:job.state,truck_id:job.truck_id,destination:job.destination,media_path:'/api/worker/media/'+job.id}:null})}
 if(path.startsWith('worker/media/')&&method==='GET'){const w=await worker(req);const job=await db().prepare('SELECT * FROM jobs WHERE id=? AND owner=?').bind(path.slice(13),w.owner).first<Row>();if(!validLease(job,w.owner,req.headers.get('x-job-lease')))throw new HttpError(409,'The analysis lease expired.');const obj=await bucket().get(job!.object_key);if(!obj)throw new HttpError(404,'Footage not found.');return new Response(obj.body,{headers:{'Content-Type':'application/octet-stream','Cache-Control':'no-store'}})}
 if(path==='worker/complete'&&method==='POST'){
  const w=await worker(req);const body=await input(req,8*1024*1024);const job=await db().prepare('SELECT * FROM jobs WHERE id=? AND owner=?').bind(body.job_id||'',w.owner).first<Row>();if(job?.status==='completed'&&job.lease_id===body.lease_id){await cleanupUpload(job);return json({ok:true,already_completed:true})};if(!validLease(job,w.owner,body.lease_id))throw new HttpError(409,'The analysis lease expired.');
  if(!Array.isArray(body.detections)||body.detections.length>5)throw new HttpError(422,'Expected up to five plate candidates.');if(!Number.isInteger(body.analyzed_frames)||body.analyzed_frames<0||body.analyzed_frames>1000000)throw new HttpError(422,'Invalid frame count.');
  const seen=new Set<string>();const detections=body.detections.map((d:Row)=>{const valid=validate(()=>validateDetection(d));if(seen.has(valid.plate))throw new HttpError(422,'Duplicate plate candidate.');seen.add(valid.plate);let jpg:Uint8Array|null=null;if(d.snapshot_base64){if(typeof d.snapshot_base64!=='string'||d.snapshot_base64.length>1400000)throw new HttpError(413,'Snapshot too large.');try{jpg=Uint8Array.from(atob(d.snapshot_base64),c=>c.charCodeAt(0))}catch{throw new HttpError(422,'Invalid snapshot.')}if(jpg[0]!==255||jpg[1]!==216||jpg[jpg.length-2]!==255||jpg[jpg.length-1]!==217)throw new HttpError(422,'Snapshot must be JPEG.')}return {...valid,jpg}});
  const saved:string[]=[];try{const prepared=[];for(const d of detections){const id=crypto.randomUUID(),key=d.jpg?'evidence/'+id+'.jpg':null;if(key){await bucket().put(key,d.jpg,{httpMetadata:{contentType:'image/jpeg'}});saved.push(key)}prepared.push({...d,id,key})}const completedAt=Date.now();const statements=[];for(const d of prepared){const {id,key}=d;statements.push(db().prepare("INSERT INTO records (id,job_id,owner,plate,state,confidence,votes,detected_at,truck_id,destination,source_filename,snapshot_key,review_status,analyzed_frames) SELECT ?,?,?,?,?,?,?,?,?,?,?,?,'pending',? WHERE EXISTS (SELECT 1 FROM jobs WHERE id=? AND lease_id=? AND status='analyzing' AND lease_until > ?)").bind(id,job!.id,w.owner,d.plate,job!.state,d.confidence,d.votes,job!.created_at,job!.truck_id,job!.destination,job!.source_filename,key,body.analyzed_frames,job!.id,body.lease_id,completedAt))}
   statements.push(db().prepare("UPDATE jobs SET status='completed',result_count=?,analyzed_frames=? WHERE id=? AND owner=? AND lease_id=? AND status='analyzing' AND lease_until > ? RETURNING id").bind(detections.length,body.analyzed_frames,job!.id,w.owner,body.lease_id,completedAt));const results=await db().batch(statements);if(!results[results.length-1].results?.length)throw new HttpError(409,'The analysis lease expired.');
  }catch(e){for(const key of saved)await bucket().delete(key);throw e}await cleanupUpload(job!);return json({ok:true,count:detections.length})
 }
 if(path==='worker/fail'&&method==='POST'){const w=await worker(req);const body=await input(req);const row=await db().prepare("UPDATE jobs SET status='failed',error=? WHERE id=? AND owner=? AND lease_id=? AND status='analyzing' AND lease_until > ? RETURNING id").bind(text(body.error,300,'Error message'),body.job_id||'',w.owner,body.lease_id||'',Date.now()).first();if(!row)throw new HttpError(409,'The analysis lease expired.');return json({ok:true})}
 if(path.startsWith('media/')&&method==='GET'){const row=await db().prepare('SELECT * FROM records WHERE id=?').bind(path.slice(6)).first<Row>();if(!row||!row.snapshot_key)throw new HttpError(404,'Snapshot not found.');if(row.review_status!=='published'){const u=await operator(req);if(row.owner!==u.userId)throw new HttpError(404,'Snapshot not found.')}const obj=await bucket().get(row.snapshot_key);if(!obj)throw new HttpError(404,'Snapshot not found.');return new Response(obj.body,{headers:{'Content-Type':'image/jpeg','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}})}
 throw new HttpError(404,'Endpoint not found.');
 }catch(e){if(e instanceof HttpError)return json({error:e.message},e.status);console.error('Tow API failure',e);return json({error:'The service is temporarily unavailable. Your form has been preserved; please try again.'},503)}}
